version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    #Persistent storage for mysql server
    volumes:
      - db_data:/var/lib/mysql
    #Establishes passwords and names
    env_file:
      - .env.txt
    #Not hardcoded, sourced from .env
    ports:
      - "${MYSQL_PORT}:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    #Always bring it up again
    restart: always
    #Suggested so that it can live update instead of rebuilding docker image.
    volumes:
      - .:/backend 
      - ./spark-apps:/opt/bitnami/spark/apps:rw
    ports:
      - "5000:5000"
    env_file:
      - .env.txt
    #Needs to be able to write to the sparks_apps_dir as well.
    environment:
      - DATABASE_URL=mysql+pymysql://root:${DB_PASSWORD}@db/my_database
      - SPARK_SHARED_DIR=/opt/bitnami/spark/apps
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:5000
    #Might delete
    stdin_open: true # For interactive shells if using Create React App
    #Makes it somewhat persistent.
    tty: true

  spark-master:
    image: apache/spark:3.5.8-scala2.12-java17-python3-ubuntu
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
    ports:
      - "8080:8080" # Spark Master Web UI
      - "7077:7077" # Spark Master service port
    volumes:
      - ./spark-apps:/opt/bitnami/spark/apps # Mount your Python scripts here

  spark-worker:
    image: apache/spark:3.5.8-scala2.12-java17-python3-ubuntu
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
    volumes:
      - ./spark-apps:/opt/bitnami/spark/apps
    depends_on:
      - spark-master
volumes:
  db_data:
