# Generated by Django 5.2.13 on 2026-05-04 05:30

import scripts.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='script',
            name='content',
        ),
        migrations.AddField(
            model_name='script',
            name='file',
            field=models.FileField(default='empty', upload_to=scripts.models.script_file_path),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='script',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
